apiVersion: v1
kind: Pod
metadata:
  name: nginx-tarde2
  labels:
    app: nginx-app
  namespace: proyecto1
spec:
  containers:
    - name: nginx-container
      image: nginx:alpine
      command: ["sh", "-c", "echo VERSION 1.0 desde $HOSTNAME > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
